name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/hello-world-docer-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        env:
          INPUT_WHO_TO_GREET: Mona Lisa Octocat
          JIRA_USER_NAME: cloudroot@dariohealth.com
          JIRA_USER_TOKEN: dummy-token
        run: |
          docker run \
          --env INPUT_WHO_TO_GREET="${{ env.INPUT_WHO_TO_GREET }}" \
          --env JIRA_USER_NAME="${{ env.INPUT_WHO_TO_GREET }}" \
          --env JIRA_USER_TOKEN="${{ env.INPUT_WHO_TO_GREET }}" \
          --rm ${{ env.TEST_TAG }}

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          jira-api: Mona Lisa Octocat
          jira-user-name: cloudroot@dariohealth.com
          jira-user-token: dummy-token
          

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.jira-api-output }}"
